require 'typhoeus'
require 'virtus'

require 'athena_health/version'
require 'athena_health/connection'
require 'athena_health/error'
require 'athena_health/endpoints/practices'
require 'athena_health/endpoints/departments'
require 'athena_health/endpoints/patients'
require 'athena_health/endpoints/appointments'
require 'athena_health/endpoints/providers'
require 'athena_health/client'
require 'athena_health/base_collection'
require 'athena_health/base_model'
require 'athena_health/practice'
require 'athena_health/practice_collection'
require 'athena_health/department'
require 'athena_health/department_collection'
require 'athena_health/balance'
require 'athena_health/patient'
require 'athena_health/patient_collection'
require 'athena_health/event'
require 'athena_health/patient_problem'
require 'athena_health/patient_problem_collection'
require 'athena_health/provider'
require 'athena_health/provider_collection'
require 'athena_health/appointment_type'
require 'athena_health/appointment_type_collection'

module AthenaHealth
end
