require 'spec_helper'

describe AthenaHealth::Patient do
  let(:patient_attributes) do
    {
      'email': 'monroe86@hotmail.com',
      'emailexists': 'true',
      'occupationcode': '123.123',
      'departmentid': '162',
      'homephone': '6102569611',
      'homebound': 'false',
      'guarantorstate': 'GA',
      'portalaccessgiven': 'false',
      'driverslicense': 'false',
      'workphone': '7257089299',
      'ethnicitycode': '123',
      'industrycode': '1234',
      'contacthomephone': '12341234',
      'contactrelationship': 'Test',
      'contactname': 'Contact name',
      'contactpreference_appointment_sms': 'false',
      'contactpreference_appointment_email': 'false',
      'contactpreference_billing_phone': 'false',
      'contactpreference_announcement_phone': 'false',
      'contactpreference_lab_sms': 'false',
      'contactpreference_lab_phone': 'false',
      'contactpreference_lab_email': 'false',
      'contactpreference_announcement_sms': 'false',
      'contactpreference_announcement_email': 'false',
      'contactpreference_appointment_phone': 'false',
      'contactpreference_billing_sms': 'false',
      'contactpreference_billing_email': 'false',
      'contactpreference': 'Work',
      'firstappointment': '10/10/2010 10:10',
      'lastappointment': '10/10/2010 10:10',
      'patientphotourl': 'photo_url',
      'mobilecarrierid': '1',
      'guarantorssn': '*****6481',
      'guarantordob': '11/24/1976',
      'zip': '13323-6882',
      'guarantoraddresssameaspatient': 'false',
      'employerphone': '123321',
      'contactmobilephone': '123231',
      'nextkinphone': '123123',
      'nextkinrelationship': 'kin relationship',
      'nextkinname': 'kin name',
      'portaltermsonfile': 'false',
      'status': 'active',
      'lastname': 'McCullough',
      'guarantorfirstname': 'Nicklaus',
      'city': 'DEVYNMOUTH',
      'ssn': '*****4181',
      'guarantoremail': 'jacky.dubuque@gmail.com',
      'guarantorcity': 'SOUTH GREGORYMOUTH',
      'guarantorzip': '96049',
      'privacyinformationverified': 'false',
      'primarydepartmentid': '162',
      'balances': [
        {
          'balance': 0,
          'departmentlist': '1,21,102,145,148,150,157,162',
          'providergroupid': '1',
          'cleanbalance': 'true'
        }
      ],
      'race': [],
      'racename': 'race name',
      'language6392code': '123',
      'primaryproviderid': '2',
      'patientphoto': 'false',
      'povertylevelincomedeclined': 'false',
      'povertylevelfamilysizedeclined': 'false',
      'caresummarydeliverypreference': 'test',
      'guarantorlastname': 'West',
      'firstname': 'Etha',
      'middlename': 'A.',
      'suffix': 'suffix',
      'preferredname': 'prefered name',
      'maritalstatus': 'marital status',
      'maritalstatusname': 'marital status name',
      'sex': 'M',
      'notes': 'notes',
      'hasmobile': 'true',
      'mobilephone': '123',
      'onlinestatementonly': 'false',
      'guarantorcountrycode': 'USA',
      'state': 'CO',
      'patientid': '5309',
      'referralsourceid': '1',
      'dob': '12/05/1937',
      'guarantorrelationshiptopatient': '13',
      'address1': '198 Emard Cove Apt. 230',
      'address2': 'Basement',
      'guarantorphone': '123',
      'countrycode': 'USA',
      'guarantoraddress1': '740 Pauline Mission',
      'guarantoraddress2': '740 NYC',
      'consenttotext': 'false',
      'consenttocall': 'false',
      'countrycode3166': 'US',
      'guarantorcountrycode3166': 'US',
      'lastemail': 'demo@athenahealth.com',
      'employerid': '1',
      'employercity': 'SOUTHBRIDGE',
      'employerstate': 'MA',
      'employerzip': '01550',
      'guarantorsuffix': 'IV',
      'guarantoremployerid': '1',
      'employername': 'RAQUEL DOUGHTY',
      'employeraddress': '8762 STONERIDGE CT',
      'preferredpronouns': 'they/them',
      'altfirstname': 'Nikki',
      'assignedsexatbirth': 'F'
    }
  end

  subject { AthenaHealth::Patient.new(patient_attributes) }

  it_behaves_like 'a model'

  it 'have proper attributes' do
    expect(subject).to have_attributes(
      emailexists: true,
      email: 'monroe86@hotmail.com',
      occupationcode: '123.123',
      departmentid: 162,
      homephone: '6102569611',
      homebound: false,
      guarantorstate: 'GA',
      portalaccessgiven: false,
      driverslicense: false,
      workphone: '7257089299',
      ethnicitycode: '123',
      industrycode: '1234',
      contacthomephone: '12341234',
      contactrelationship: 'Test',
      contactname: 'Contact name',
      contactpreference_appointment_sms: false,
      contactpreference_appointment_email: false,
      contactpreference_billing_phone: false,
      contactpreference_announcement_phone: false,
      contactpreference_lab_sms: false,
      contactpreference_lab_phone: false,
      contactpreference_lab_email: false,
      contactpreference_announcement_sms: false,
      contactpreference_announcement_email: false,
      contactpreference_appointment_phone: false,
      contactpreference_billing_sms: false,
      contactpreference_billing_email: false,
      contactpreference: 'Work',
      firstappointment: '10/10/2010 10:10',
      lastappointment: '10/10/2010 10:10',
      patientphotourl: 'photo_url',
      mobilecarrierid: 1,
      guarantorssn: '*****6481',
      guarantordob: '11/24/1976',
      zip: '13323-6882',
      guarantoraddresssameaspatient: false,
      employerphone: '123321',
      contactmobilephone: '123231',
      nextkinphone: '123123',
      nextkinrelationship: 'kin relationship',
      nextkinname: 'kin name',
      portaltermsonfile: false,
      status: 'active',
      lastname: 'McCullough',
      guarantorfirstname: 'Nicklaus',
      city: 'DEVYNMOUTH',
      ssn: '*****4181',
      guarantoremail: 'jacky.dubuque@gmail.com',
      guarantorcity: 'SOUTH GREGORYMOUTH',
      guarantorzip: '96049',
      privacyinformationverified: false,
      primarydepartmentid: 162,
      race: [],
      racename: 'race name',
      language6392code: '123',
      primaryproviderid: 2,
      patientphoto: false,
      povertylevelincomedeclined: false,
      povertylevelfamilysizedeclined: false,
      caresummarydeliverypreference: 'test',
      guarantorlastname: 'West',
      firstname: 'Etha',
      middlename: 'A.',
      suffix: 'suffix',
      preferredname: 'prefered name',
      maritalstatus: 'marital status',
      maritalstatusname: 'marital status name',
      sex: 'M',
      notes: 'notes',
      hasmobile: true,
      mobilephone: '123',
      onlinestatementonly: false,
      guarantorcountrycode: 'USA',
      state: 'CO',
      patientid: 5309,
      referralsourceid: 1,
      dob: '12/05/1937',
      guarantorrelationshiptopatient: 13,
      address1: '198 Emard Cove Apt. 230',
      address2: 'Basement',
      guarantorphone: '123',
      countrycode: 'USA',
      guarantoraddress1: '740 Pauline Mission',
      guarantoraddress2: '740 NYC',
      consenttotext: false,
      consenttocall: false,
      countrycode3166: 'US',
      guarantorcountrycode3166: 'US',
      fullname: 'Etha A. McCullough',
      lastemail: 'demo@athenahealth.com',
      employerid: 1,
      employercity: 'SOUTHBRIDGE',
      employerstate: 'MA',
      employerzip: '01550',
      guarantorsuffix: 'IV',
      guarantoremployerid: 1,
      employername: 'RAQUEL DOUGHTY',
      employeraddress: '8762 STONERIDGE CT',
      preferredpronouns: 'they/them',
      altfirstname: 'Nikki',
      assignedsexatbirth: 'F'
    )

    expect(subject.balances.map(&:class)).to eq [AthenaHealth::Balance]
  end
end
